AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation for deploying Stack set to Singapore and Tokyo
Parameters:
  AdministrationRoleName:
    Type: String
    Default: AWSCloudFormationStackSetAdministrationRole
    Description: "The name of the administration role. Defaults to 'AWSCloudFormationStackSetAdministrationRole'."
  ExecutionRoleName:
    Type: String
    Default: AWSCloudFormationStackSetExecutionRole
    Description: "The name of the execution role that can assume this role. Defaults to 'AWSCloudFormationStackSetExecutionRole'."
  PrimaryRegion:
    Type: String
    Default: ap-southeast-1 # Singapore
    
Resources:
  VPCStackSet:
    Type: 'AWS::CloudFormation::StackSet'
    Properties:
      StackSetName: ws02-vpc
      Description: VPC stack set on Singapore and Tokyo
      PermissionModel: SELF_MANAGED
      ExecutionRoleName: !Ref ExecutionRoleName
      ManagedExecution:
        Active: true
      Tags:
        - Key: test
          Value: true
      TemplateURL: https://tvm-cf-templates.s3.ap-southeast-1.amazonaws.com/vpc.yml
      Parameters:
        - ParameterKey: EnvironmentName
          ParameterValue: ws02-vpc
      OperationPreferences:
        FailureToleranceCount: 0
        MaxConcurrentCount: 1
        RegionConcurrencyType: PARALLEL
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref AWS::AccountId
          Regions:
          - ap-southeast-1 # Singapore
          # - ap-northeast-1 # Tokyo
            
  ECSStackSet:
    Type: 'AWS::CloudFormation::StackSet'
    DependsOn: VPCStackSet
    Properties:
      StackSetName: ws02-ecs
      Description: ECS stack set on Singapore and Tokyo
      PermissionModel: SELF_MANAGED
      ExecutionRoleName: !Ref ExecutionRoleName
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_AUTO_EXPAND
      ManagedExecution:
        Active: true
      Tags:
        - Key: test
          Value: true
      TemplateURL: https://tvm-cf-templates.s3.ap-southeast-1.amazonaws.com/main.yml
      OperationPreferences:
        FailureToleranceCount: 0
        MaxConcurrentCount: 1
        RegionConcurrencyType: PARALLEL
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref AWS::AccountId
          Regions:
            - ap-southeast-1 # Singapore
            # - ap-northeast-1 # Tokyo

  # DataBaseStackSet:
  #   Type: 'AWS::CloudFormation::StackSet'
  #   # DeletionPolicy: Retain
  #   DependsOn: VPCStackSet
  #   Properties:
  #     StackSetName: ws02-database
  #     Description: Database
  #     PermissionModel: SELF_MANAGED
  #     ExecutionRoleName: !Ref ExecutionRoleName
  #     # Capabilities:
  #     #   - CAPABILITY_IAM
  #     #   - CAPABILITY_AUTO_EXPAND
  #     ManagedExecution:
  #       Active: true
  #     Tags:
  #       - Key: test
  #         Value: true
  #     TemplateURL: https://tvm-cf-templates.s3.ap-southeast-1.amazonaws.com/database.yml
  #     Parameters:
  #       - ParameterKey: DBName
  #         ParameterValue: ws02instance
  #       - ParameterKey: VpcStackName
  #         ParameterValue: ws02-vpc
  #       - ParameterKey: SourceDBInstanceIdentifier
  #         ParameterValue: !Sub arn:aws:rds:${PrimaryRegion}:${AWS::AccountId}:db:ws02instance
  #     OperationPreferences:
  #       FailureToleranceCount: 0
  #       MaxConcurrentCount: 1
  #       RegionConcurrencyType: SEQUENTIAL
  #       RegionOrder:
  #         - ap-southeast-1
  #         - ap-northeast-1
  #     StackInstancesGroup:
  #       - DeploymentTargets:
  #           Accounts:
  #             - !Ref AWS::AccountId
  #         Regions:
  #           - ap-southeast-1 # Singapore
  #           - ap-northeast-1 # Tokyo