AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repository
Parameters:
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
  SourceDBInstanceIdentifier:
    Type: String
    Default: ws02replica
  SourceRegion:
    Type: String
  VpcStackName: 
    Type: String

Resources:
  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: ws02 private subnets 
      DBSubnetGroupName: ws02
      # Get from VPC
      SubnetIds: 
        - !Select
          - 0
          - !Split
            - ','
            - Fn::ImportValue:
                Fn::Sub: ${VpcStackName}-PrivateSubnets
        - !Select
          - 1
          - !Split
            - ','
            - Fn::ImportValue:
                Fn::Sub: ${VpcStackName}-PrivateSubnets
  RegionReadReplica:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: !Ref DBInstanceClass
      SourceDBInstanceIdentifier: !Ref SourceDBInstanceIdentifier
      SourceRegion: !Ref SourceRegion
      MultiAZ: false
