AWSTemplateFormatVersion: '2010-09-09'
Description: An example service that deploys in AWS VPC networking mode on EC2 capacity. Service uses a capacity provider to request EC2 instances to run on. Service runs with networking in private subnets, but still accessible to the internet via a load balancer hosted in public subnets.
Parameters:
  ELBTargetGroupArn:
    Type: String
    Description: ALB Stack Name from ECS
  ClusterName:
    Type: String
    Description: ECS cluster
  CapacityProvider:
    Type: String
    Description: ECS Capacity Provider
  TaskExecutionRoleArn:
    Type: String
    Description: Task Role
  TaskRole:
    Type: String
    Description: Task Role
  VpcStackName:
    Type: String
    Description: The name of VPC stack
  ServiceName:
    Type: String
    Description: A name for the service
  ImageUrl:
    Type: String
    Default: public.ecr.aws/docker/library/nginx:latest
    Description: The url of a docker image that contains the application process that will handle the traffic for this service
  ContainerCpu:
    Type: Number
    Default: 256
    Description: How much CPU to give the container. 1024 is 1 CPU
  ContainerMemory:
    Type: Number
    Default: 512
    Description: How much memory in megabytes to give the container
  ContainerPort:
    Type: Number
    Default: 80
    Description: What port that the application expects traffic on
  DesiredCount:
    Type: Number
    Default: 0
    Description: How many copies of the service task to run
  ScalingRoleArn:
    Type: String
    Default: arn:aws:iam::761048055120:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
    Description: Scaling Role for ECS service
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Cpu: !Ref ContainerCpu
          Memory: !Ref ContainerMemory
          Image: !Ref ImageUrl
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: !Ref ContainerPort
              AppProtocol: http
              Name: nginx-svc
          LogConfiguration:
            LogDriver: awslogs
            Options:
              mode: non-blocking
              max-buffer-size: 25m
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref ServiceName
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref ClusterName
      EnableExecuteCommand: true
      PlacementStrategies:
        - Field: cpu
          Type: binpack
      CapacityProviderStrategy:
        - Base: 0
          CapacityProvider: !Ref CapacityProvider
          Weight: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref ServiceSecurityGroup
          Subnets:
            - Fn::ImportValue:
                Fn::Sub: ${VpcStackName}-PrivateSubnet1
            - Fn::ImportValue:
                Fn::Sub: ${VpcStackName}-PrivateSubnet2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DeploymentController:
        Type: ECS
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref ELBTargetGroupArn
      ServiceConnectConfiguration:
        Enabled: True
        LogConfiguration:
          LogDriver: awslogs
          Options:
            mode: non-blocking
            max-buffer-size: 25m
            awslogs-create-group: True
            awslogs-group: !Sub /ecs/${ServiceName}
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: ecs
        Namespace: !Ref ClusterName
        Services:
          - ClientAliases:
              - Port: 80
            PortName: nginx-svc
  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for service
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: ${VpcStackName}-VpcId
      SecurityGroupIngress:
        - CidrIp: 
            Fn::ImportValue:
                Fn::Sub: ${VpcStackName}-CIDR
          IpProtocol: -1
  LogGroup:
    Type: AWS::Logs::LogGroup

  ScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: Service
    Properties:
      MaxCapacity: 3
      MinCapacity: 1
      ResourceId: !Join ["/", [service, !Ref ClusterName, !GetAtt Service.Name]]
      RoleARN: !Ref ScalingRoleArn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  TargetTrackingScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: cpu75-target-tracking-scaling-policy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 75.0
        ScaleInCooldown: 30
        ScaleOutCooldown: 30
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization